import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const booksData = [
  { title: "Carta ao Pai", author: "Franz Kafka", genre: "Biografia", year: 1919, pages: 128, rating: 5, synopsis: "Escrita em 1919, esta que é uma das mais importantes cartas da literatura universal jamais chegou ao seu destino. Nela, o autor de A metamorfose expõe as incompatibilidades e a relação conflituosa entre um filho artista e um pai autoritário.", cover: "/covers/carta-ao-pai.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "A Metamorfose", author: "Franz Kafka", genre: "Ficção", year: 1915, pages: 96, rating: 5, synopsis: "Nesta que é sua mais célebre novela, Kafka narra a história do caixeiro-viajante Gregor Samsa, que um dia acorda transformado num inseto monstruoso. A partir daí, a história aborda o isolamento, a angústia e a inadequação do indivíduo perante uma sociedade opressora e indiferente.", cover: "/covers/metamorfose.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "Noites Brancas", author: "Fiódor Dostoiévski", genre: "Romance", year: 1848, pages: 96, rating: 4, synopsis: "Em São Petersburgo, um sonhador solitário conhece uma jovem durante quatro noites mágicas, vivendo um breve e melancólico romance que explora a solidão e a idealização do amor.", cover: "/covers/noites-brancas.jpg", publisher: "Editora 34", language: "Português", series: "" },
  { title: "Os Irmãos Karamázov", author: "Fiódor Dostoiévski", genre: "Filosofia", year: 1880, pages: 840, rating: 5, synopsis: "O último e mais grandioso romance de Dostoiévski, que mergulha em questões de fé, dúvida, e moralidade através do parricídio que envolve os três irmãos Karamázov e seu pai.", cover: "/covers/irmaos-karamazov.jpg", publisher: "Editora 34", language: "Português", series: "" },
  { title: "Memórias do Subsolo", author: "Fiódor Dostoiévski", genre: "Filosofia", year: 1864, pages: 160, rating: 5, synopsis: "O monólogo de um homem amargo e paradoxal que expõe a irracionalidade da natureza humana como uma rebelião contra o determinismo. Uma obra seminal do existencialismo.", cover: "/covers/memorias-subsolo.jpg", publisher: "Editora 34", language: "Português", series: "" },
  { title: "Crime e Castigo", author: "Fiódor Dostoiévski", genre: "Ficção", year: 1866, pages: 560, rating: 5, synopsis: "A história de Raskólnikov, um jovem estudante que comete um assassinato para testar suas teorias morais e é levado a uma jornada psicológica de culpa, tormento e busca por redenção.", cover: "/covers/crime-e-castigo.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "Um Artista da Fome", author: "Franz Kafka", genre: "Ficção", year: 1922, pages: 104, rating: 4, synopsis: "Uma coletânea de contos que explora a alienação e o absurdo, incluindo a história de um artista cujo único talento é o jejum público, mas que se torna obsoleto num mundo que já não o compreende.", cover: "/covers/artista-fome.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "O Castelo", author: "Franz Kafka", genre: "Ficção", year: 1926, pages: 368, rating: 4, synopsis: "Um romance inacabado sobre K., um agrimensor que luta para conseguir acesso a um misterioso castelo e às autoridades que o governam, numa batalha fútil contra uma burocracia impenetrável e labiríntica.", cover: "/covers/o-castelo.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "A Náusea", author: "Jean-Paul Sartre", genre: "Filosofia", year: 1938, pages: 240, rating: 5, synopsis: "Em forma de diário, o historiador Antoine Roquentin registra sua 'náusea', uma sensação avassaladora da contingência e do absurdo da existência ao confrontar a realidade nua e crua dos objetos e de si mesmo.", cover: "/covers/a-nausea.jpg", publisher: "Nova Fronteira", language: "Português", series: "" },
  { title: "A Peste", author: "Albert Camus", genre: "Ficção", year: 1947, pages: 304, rating: 5, synopsis: "Uma alegoria sobre a resistência humana e a solidariedade diante do absurdo, narrando a luta de uma cidade argelina isolada por uma epidemia devastadora.", cover: "/covers/a-peste.jpg", publisher: "Record", language: "Português", series: "" },
  { title: "Memórias Póstumas de Brás Cubas", author: "Machado de Assis", genre: "Literatura Brasileira", year: 1881, pages: 256, rating: 5, synopsis: "Um 'defunto autor' narra sua vida com ironia, pessimismo e digressões filosóficas, expondo a mediocridade da elite de seu tempo. Uma obra revolucionária da literatura mundial.", cover: "/covers/memorias-postumas.jpg", publisher: "Principis", language: "Português", series: "" },
  { title: "O Diário de Anne Frank", author: "Anne Frank", genre: "Biografia", year: 1947, pages: 352, rating: 5, synopsis: "O testemunho íntimo e comovente de uma jovem judia escondida dos nazistas durante a Segunda Guerra Mundial, um símbolo da resiliência humana e um relato poderoso sobre a adolescência em meio ao terror.", cover: "/covers/anne-frank.jpg", publisher: "Record", language: "Português", series: "" },
  { title: "A Autobiografia de Malcolm X", author: "Malcolm X, Alex Haley", genre: "Biografia", year: 1965, pages: 464, rating: 5, synopsis: "A poderosa história de transformação de Malcolm X, desde sua juventude no crime até se tornar um dos mais influentes líderes do movimento dos direitos civis.", cover: "/covers/malcolm-x.jpg", publisher: "Record", language: "Português", series: "" },
  { title: "De Profundis", author: "Oscar Wilde", genre: "Biografia", year: 1905, pages: 160, rating: 4, synopsis: "Uma longa e pungente carta escrita por Oscar Wilde na prisão, refletindo sobre sua vida, seu amor, sua arte e sua espiritualidade em meio ao sofrimento.", cover: "/covers/de-profundis.jpg", publisher: "L&PM", language: "Português", series: "" },
  { title: "Anna Karenina", author: "Liev Tolstói", genre: "Romance", year: 1877, pages: 864, rating: 5, synopsis: "Uma trágica história de amor e adultério na alta sociedade russa, contrastando a paixão destrutiva de Anna com a busca por sentido na vida do proprietário de terras Levin.", cover: "/covers/anna-karenina.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "O Mito de Sísifo", author: "Albert Camus", genre: "Filosofia", year: 1942, pages: 128, rating: 5, synopsis: "Um ensaio filosófico fundamental sobre o absurdo da existência. Camus argumenta que, mesmo diante de uma luta eterna e sem sentido, a consciência e a revolta podem dar valor à vida, e devemos imaginar Sísifo feliz.", cover: "/covers/mito-sisifo.jpg", publisher: "Record", language: "Português", series: "" },
  { title: "A Hora da Estrela", author: "Clarice Lispector", genre: "Literatura Brasileira", year: 1977, pages: 88, rating: 5, synopsis: "A comovente história de Macabéa, uma datilógrafa nordestina anônima e alienada no Rio de Janeiro, cuja vida miserável é narrada por um escritor em crise existencial que reflete sobre a pobreza e a condição humana.", cover: "/covers/hora-estrela.jpg", publisher: "Rocco", language: "Português", series: "" },
  { title: "O Cortiço", author: "Aluísio Azevedo", genre: "Literatura Brasileira", year: 1890, pages: 288, rating: 4, synopsis: "Um retrato naturalista da vida em um cortiço no Rio de Janeiro do século XIX, mostrando a ascensão social do ambicioso João Romão e a mistura explosiva de raças, classes e paixões humanas.", cover: "/covers/o-cortico.jpg", publisher: "Principis", language: "Português", series: "" },
  { title: "Vidas Secas", author: "Graciliano Ramos", genre: "Literatura Brasileira", year: 1938, pages: 176, rating: 5, synopsis: "A luta de uma família de retirantes nordestinos contra a seca e a miséria, narrada com uma linguagem enxuta e poderosa, focando na desumanização dos personagens e na sua relação com o ambiente hostil.", cover: "/covers/vidas-secas.jpg", publisher: "Record", language: "Português", series: "" },
  { title: "Coraline", author: "Neil Gaiman", genre: "Fantasia", year: 2002, pages: 162, rating: 5, synopsis: "Entediada em sua nova casa, a jovem Coraline descobre uma porta secreta que a leva a uma versão alternativa e sinistra de sua própria vida, com uma 'Outra Mãe' que a quer para sempre, num conto de fadas sombrio e arrepiante.", cover: "/covers/coraline.jpg", publisher: "Intrínseca", language: "Português", series: "" },
  { title: "Jurassic Park", author: "Michael Crichton", genre: "Ficção Científica", year: 1990, pages: 448, rating: 5, synopsis: "A teoria do caos se torna realidade quando um parque temático com dinossauros clonados em uma ilha remota sai terrivelmente do controle, transformando o sonho da bioengenharia em um pesadelo de sobrevivência contra predadores pré-históricos.", cover: "/covers/jurassic-park.jpg", publisher: "Aleph", language: "Português", series: "Jurassic Park (Livro 1)" },
  { title: "O Mundo Perdido", author: "Michael Crichton", genre: "Ficção Científica", year: 1995, pages: 432, rating: 4, synopsis: "Seis anos após o desastre do Jurassic Park, o matemático Ian Malcolm descobre que uma segunda ilha, o 'Sítio B', onde os dinossauros eram criados, foi abandonada. Relutantemente, ele se junta a uma expedição de resgate ao local, descobrindo que a natureza encontrou um caminho para prosperar sem a intervenção humana.", cover: "/covers/o-mundo-perdido.jpg", publisher: "Aleph", language: "Português", series: "Jurassic Park (Livro 2)" },
  { title: "Heartstopper: Volume 1", author: "Alice Oseman", genre: "Romance", year: 2019, pages: 288, rating: 5, synopsis: "Charlie, um garoto abertamente gay e ansioso, e Nick, um jogador de rúgbi alegre e de bom coração, se conhecem e descobrem que sua amizade pode ser algo mais. Uma história sobre amor, amizade, lealdade e saúde mental.", cover: "/covers/heartstopper-1.jpg", publisher: "Seguinte", language: "Português", series: "Heartstopper (Livro 1)" },
  { title: "Heartstopper: Volume 2", author: "Alice Oseman", genre: "Romance", year: 2019, pages: 320, rating: 5, synopsis: "Nick e Charlie navegam seus sentimentos um pelo outro enquanto lidam com as complexidades de sair do armário e os primeiros passos de um relacionamento, apoiando-se mutuamente em cada nova descoberta.", cover: "/covers/heartstopper-2.jpg", publisher: "Seguinte", language: "Português", series: "Heartstopper (Livro 2)" },
  { title: "Heartstopper: Volume 3", author: "Alice Oseman", genre: "Romance", year: 2020, pages: 384, rating: 5, synopsis: "O relacionamento de Nick e Charlie se aprofunda durante uma viagem escolar a Paris, mas novos desafios, como a pressão de se assumir para amigos e família, e as inseguranças pessoais, surgem no caminho.", cover: "/covers/heartstopper-3.jpg", publisher: "Seguinte", language: "Português", series: "Heartstopper (Livro 3)" },
  { title: "Heartstopper: Volume 4", author: "Alice Oseman", genre: "Romance", year: 2021, pages: 384, rating: 5, synopsis: "Charlie e Nick dizem 'eu te amo' pela primeira vez e enfrentam juntos as dificuldades dos transtornos alimentares e da saúde mental de Charlie, fortalecendo seu vínculo e aprendendo a importância do apoio mútuo.", cover: "/covers/heartstopper-4.jpg", publisher: "Seguinte", language: "Português", series: "Heartstopper (Livro 4)" },
  { title: "Heartstopper: Volume 5", author: "Alice Oseman", genre: "Romance", year: 2023, pages: 336, rating: 5, synopsis: "Com o fim do ensino médio se aproximando, Nick e Charlie olham para o futuro e os desafios da universidade, explorando a possibilidade de um relacionamento à distância e planejando os próximos passos de suas vidas juntos.", cover: "/covers/heartstopper-5.jpg", publisher: "Seguinte", language: "Português", series: "Heartstopper (Livro 5)" },
  { title: "Five Nights at Freddy's: Olhos Prateados", author: "Scott Cawthon & Kira Breed-Wrisley", genre: "Terror", year: 2015, pages: 432, rating: 4, synopsis: "Dez anos após os terríveis assassinatos na Freddy Fazbear's Pizza, Charlie e seus amigos de infância se reúnem na cidade e se encontram presos na pizzaria abandonada, apenas para descobrir que os animatrônicos ainda estão lá e buscam vingança.", cover: "/covers/fnaf-olhos-prateados.jpg", publisher: "Intrínseca", language: "Português", series: "Five Nights at Freddy's (Trilogia 1, Livro 1)" },
  { title: "Five Nights at Freddy's: Os Distorcidos", author: "Scott Cawthon & Kira Breed-Wrisley", genre: "Terror", year: 2017, pages: 304, rating: 4, synopsis: "Um ano após os eventos de 'Olhos Prateados', Charlie se vê assombrada por novos animatrônicos ainda mais grotescos e aterrorizantes que parecem caçá-la, enquanto a linha entre realidade e pesadelo se desfaz.", cover: "/covers/fnaf-os-distorcidos.jpg", publisher: "Intrínseca", language: "Português", series: "Five Nights at Freddy's (Trilogia 1, Livro 2)" },
  { title: "Five Nights at Freddy's: A Última Porta", author: "Scott Cawthon & Kira Breed-Wrisley", genre: "Terror", year: 2018, pages: 352, rating: 4, synopsis: "Na conclusão da trilogia original, Charlie enfrenta a verdade chocante sobre seu pai, o criador dos animatrônicos, e os segredos sombrios por trás da Fazbear Entertainment e de suas próprias criações.", cover: "/covers/fnaf-a-ultima-porta.jpg", publisher: "Intrínseca", language: "Português", series: "Five Nights at Freddy's (Trilogia 1, Livro 3)" },
  { title: "Five Nights at Freddy's: Into the Pit", author: "Scott Cawthon & Elley Cooper", genre: "Terror", year: 2019, pages: 224, rating: 4, synopsis: "A primeira da série Fazbear Frights, apresentando três contos sinistros sobre desejos sombrios, um animatrônico implacável que surge de uma piscina de bolinhas e viagens no tempo na pizzaria original.", cover: "/covers/fnaf-into-the-pit.jpg", publisher: "Intrínseca", language: "Português", series: "Fazbear Frights (Livro 1)" },
  { title: "Five Nights at Freddy's: Fetch", author: "Scott Cawthon & Carly Anne West", genre: "Terror", year: 2020, pages: 224, rating: 4, synopsis: "Três novas histórias de terror, incluindo um animatrônico que busca itens via mensagens de texto com consequências mortais, um jovem que se sente substituído e um vislumbre da ciência por trás dos animatrônicos.", cover: "/covers/fnaf-fetch.jpg", publisher: "Intrínseca", language: "Português", series: "Fazbear Frights (Livro 2)" },
  { title: "Five Nights at Freddy's: 1:35AM", author: "Scott Cawthon & Elley Cooper", genre: "Terror", year: 2020, pages: 240, rating: 4, synopsis: "A escuridão se aprofunda com mais três histórias assustadoras sobre uma jovem assombrada por um despertador, um garoto que se apaixona por um animatrônico e os perigos da engenharia reversa das criações de Fazbear.", cover: "/covers/fnaf-135am.jpg", publisher: "Intrínseca", language: "Português", series: "Fazbear Frights (Livro 3)" },
  { title: "Harry Potter e a Pedra Filosofal", author: "J.K. Rowling", genre: "Fantasia", year: 1997, pages: 223, rating: 5, synopsis: "Harry Potter, um garoto órfão, descobre em seu 11º aniversário que é um bruxo e que uma vaga o aguarda na Escola de Magia e Bruxaria de Hogwarts. Lá, ele faz amigos, descobre um mundo de magia e enfrenta os primeiros indícios do retorno de Lord Voldemort.", cover: "/covers/pedra-filosofal.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 1)" },
  { title: "Harry Potter e a Câmara Secreta", author: "J.K. Rowling", genre: "Fantasia", year: 1998, pages: 287, rating: 5, synopsis: "O segundo ano de Harry em Hogwarts é marcado por uma ameaça sinistra que assombra os corredores, petrificando os alunos. Harry e seus amigos devem desvendar os segredos da Câmara Secreta antes que seja tarde demais.", cover: "/covers/camara-secreta.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 2)" },
  { title: "Harry Potter e o Prisioneiro de Azkaban", author: "J.K. Rowling", genre: "Fantasia", year: 1999, pages: 348, rating: 5, synopsis: "No terceiro ano, Harry descobre sobre Sirius Black, um prisioneiro perigoso que fugiu de Azkaban e que todos acreditam ser o responsável pela morte de seus pais e estar agora à sua caça.", cover: "/covers/prisioneiro-de-azkaban.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 3)" },
  { title: "Harry Potter e o Cálice de Fogo", author: "J.K. Rowling", genre: "Fantasia", year: 2000, pages: 636, rating: 5, synopsis: "Hogwarts sedia o Torneio Tribruxo, um evento mágico e perigoso. Misteriosamente, Harry é escolhido como um dos campeões, forçando-o a competir em tarefas mortais enquanto Lord Voldemort finalmente ressurge.", cover: "/covers/calice-de-fogo.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 4)" },
  { title: "Harry Potter e a Ordem da Fênix", author: "J.K. Rowling", genre: "Fantasia", year: 2003, pages: 766, rating: 5, synopsis: "Com o retorno de Voldemort sendo negado pelo Ministério da Magia, Harry e seus amigos formam a 'Armada de Dumbledore' para se prepararem para a guerra que se aproxima, enquanto enfrentam a tirania de Dolores Umbridge em Hogwarts.", cover: "/covers/ordem-da-fenix.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 5)" },
  { title: "Harry Potter e o Enigma do Príncipe", author: "J.K. Rowling", genre: "Fantasia", year: 2005, pages: 432, rating: 5, synopsis: "No sexto ano de Harry em Hogwarts, ele descobre mais sobre o passado sombrio de Lord Voldemort com a ajuda de Dumbledore e um misterioso livro de poções pertencente ao 'Príncipe Mestiço', enquanto o poder do Lorde das Trevas cresce.", cover: "/covers/enigma-do-principe.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 6)" },
  { title: "Harry Potter e as Relíquias da Morte", author: "J.K. Rowling", genre: "Fantasia", year: 2007, pages: 592, rating: 5, synopsis: "No capítulo final, Harry, Rony e Hermione deixam Hogwarts para embarcar em uma perigosa missão: encontrar e destruir as Horcruxes de Voldemort, culminando na batalha final pelo destino do mundo bruxo.", cover: "/covers/reliquias-da-morte.jpg", publisher: "Rocco", language: "Português", series: "Harry Potter (Livro 7)" },
  { title: "A Guerra dos Tronos", author: "George R. R. Martin", genre: "Fantasia", year: 1996, pages: 592, rating: 5, synopsis: "Nos Sete Reinos de Westeros, a luta pelo Trono de Ferro começa entre as grandes casas nobres, desencadeando uma guerra de traição, poder e honra, enquanto uma antiga ameaça desperta no Norte.", cover: "/covers/a-guerra-dos-tronos.jpg", publisher: "Suma", language: "Português", series: "As Crônicas de Gelo e Fogo (Livro 1)" },
  { title: "A Fúria dos Reis", author: "George R. R. Martin", genre: "Fantasia", year: 1998, pages: 648, rating: 5, synopsis: "Enquanto a guerra dos cinco reis assola Westeros, um cometa vermelho anuncia mais derramamento de sangue e a ascensão de novas ameaças. Tyrion Lannister luta para controlar a capital enquanto Stannis Baratheon marcha para o sul.", cover: "/covers/a-furia-dos-reis.jpg", publisher: "Suma", language: "Português", series: "As Crônicas de Gelo e Fogo (Livro 2)" },
  { title: "A Tormenta de Espadas", author: "George R. R. Martin", genre: "Fantasia", year: 2000, pages: 888, rating: 5, synopsis: "A guerra se intensifica com traições chocantes, batalhas monumentais e o avanço dos Outros para além da Muralha. O Casamento Vermelho muda para sempre o destino das grandes casas de Westeros.", cover: "/covers/a-tormenta-de-espadas.jpg", publisher: "Suma", language: "Português", series: "As Crônicas de Gelo e Fogo (Livro 3)" },
  { title: "O Festim dos Corvos", author: "George R. R. Martin", genre: "Fantasia", year: 2005, pages: 648, rating: 4, synopsis: "Após a guerra, os Sete Reinos tentam se reconstruir sob o reinado dos Lannister, mas novas intrigas políticas e religiosas surgem em Porto Real e nas Ilhas de Ferro, ameaçando a frágil paz.", cover: "/covers/o-festim-dos-corvos.jpg", publisher: "Suma", language: "Português", series: "As Crônicas de Gelo e Fogo (Livro 4)" },
  { title: "A Dança dos Dragões", author: "George R. R. Martin", genre: "Fantasia", year: 2011, pages: 856, rating: 5, synopsis: "No Leste, Daenerys Targaryen luta para governar Meereen, enquanto no Norte, Jon Snow enfrenta desafios como Senhor Comandante da Patrulha da Noite. Personagens há muito perdidos retornam, e novos conflitos se preparam.", cover: "/covers/a-danca-dos-dragoes.jpg", publisher: "Suma", language: "Português", series: "As Crônicas de Gelo e Fogo (Livro 5)" },
  { title: "O Hobbit", author: "J.R.R. Tolkien", genre: "Fantasia", year: 1937, pages: 310, rating: 5, synopsis: 'A jornada inesperada de Bilbo Bolseiro, um hobbit que prefere o conforto de sua casa, mas que é levado por um grupo de anões e o mago Gandalf a uma grande aventura para recuperar um tesouro guardado pelo dragão Smaug.', cover: "/covers/hobbit.jpg", publisher: "HarperCollins", language: "Português", series: "" },
  { title: "O Pequeno Príncipe", author: "Antoine de Saint-Exupéry", genre: "Fantasia", year: 1943, pages: 96, rating: 5, synopsis: "Um piloto de avião cai no deserto do Saara e encontra um pequeno príncipe vindo de outro planeta. Uma história poética e filosófica sobre amizade, amor, perda e o que é verdadeiramente essencial na vida.", cover: "/covers/o-pequeno-principe.jpg", publisher: "Agir", language: "Português", series: "" },
  { title: "1984", author: "George Orwell", genre: "Ficção Científica", year: 1949, pages: 328, rating: 5, synopsis: "Em um futuro distópico onde o Grande Irmão vigia a todos, Winston Smith, um funcionário do Partido, se rebela contra o regime totalitário que controla a história, o pensamento e a verdade, em uma luta desesperada por liberdade e individualidade.", cover: "/covers/1984.jpg", publisher: "Companhia das Letras", language: "Português", series: "" },
  { title: "Solitaire", author: "Alice Oseman", genre: "Romance", year: 2014, pages: 400, rating: 4, synopsis: "Tori Spring é uma adolescente pessimista que não acredita em amizade ou amor. Mas quando um blog anônimo chamado 'Solitaire' começa a fazer pegadinhas cada vez mais perigosas em sua escola, ela é forçada a sair de sua zona de conforto e confrontar seus próprios demônios.", cover: "/covers/solitaire.jpg", publisher: "Seguinte", language: "Português", series: "" },
];

async function main() {
  await prisma.book.deleteMany({});
  await prisma.genre.deleteMany({});

  const uniqueGenres = [...new Set(booksData.map(book => book.genre).filter(Boolean))];

  for (const genreName of uniqueGenres) {
    if (genreName) {
      await prisma.genre.create({
        data: { name: genreName },
      });
    }
  }

  for (const [index, book] of booksData.entries()) {
    await prisma.book.create({
      data: {
        id: String(index + 1),
        title: book.title,
        author: book.author,
        coverUrl: book.cover,
        year: book.year,
        pages: book.pages,
        rating: book.rating,
        synopsis: book.synopsis,
        genreName: book.genre,
        publisher: book.publisher,
        language: book.language,
        series: book.series,
        status: 'QUERO_LER',
        currentPage: 0,
      }
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });